-- apply changes
create table guilds (
  id                            bigint generated by default as identity not null,
  discord_id                    varchar(255) not null,
  version                       bigint not null,
  when_created                  timestamptz not null,
  when_modified                 timestamptz not null,
  constraint uq_guilds_discord_id unique (discord_id),
  constraint pk_guilds primary key (id)
);

create table member (
  id                            bigint generated by default as identity not null,
  discord_id                    varchar(255) not null,
  version                       bigint not null,
  when_created                  timestamptz not null,
  when_modified                 timestamptz not null,
  constraint uq_member_discord_id unique (discord_id),
  constraint pk_member primary key (id)
);

create table messages (
  id                            bigint generated by default as identity not null,
  author_id                     bigint not null,
  discord_id                    varchar(255) not null,
  guild_id                      bigint not null,
  body                          varchar(255) not null,
  parent_message_id             bigint,
  version                       bigint not null,
  when_created                  timestamptz not null,
  when_modified                 timestamptz not null,
  constraint pk_messages primary key (id)
);

create table guildmemberrelation (
  id                            bigint generated by default as identity not null,
  guild_id                      bigint not null,
  member_id                     bigint not null,
  version                       bigint not null,
  when_created                  timestamptz not null,
  when_modified                 timestamptz not null,
  constraint uq_guildmemberrelation_guild_id_member_id unique (guild_id,member_id),
  constraint pk_guildmemberrelation primary key (id)
);

create index ix_messages_author_id on messages (author_id);
alter table messages add constraint fk_messages_author_id foreign key (author_id) references member (id) on delete restrict on update restrict;

create index ix_messages_guild_id on messages (guild_id);
alter table messages add constraint fk_messages_guild_id foreign key (guild_id) references guilds (id) on delete restrict on update restrict;

create index ix_messages_parent_message_id on messages (parent_message_id);
alter table messages add constraint fk_messages_parent_message_id foreign key (parent_message_id) references messages (id) on delete restrict on update restrict;

create index ix_guildmemberrelation_guild_id on guildmemberrelation (guild_id);
alter table guildmemberrelation add constraint fk_guildmemberrelation_guild_id foreign key (guild_id) references guilds (id) on delete restrict on update restrict;

create index ix_guildmemberrelation_member_id on guildmemberrelation (member_id);
alter table guildmemberrelation add constraint fk_guildmemberrelation_member_id foreign key (member_id) references member (id) on delete restrict on update restrict;

